### ISSUE TITLE
how to compile cache.cpp ?

### ISSUE THREAD

**Issue by jgphpc** [bcumming/stream-clean#1]
CC -std=c++11 cache.cpp 

```
cache.cpp:16:27: error: '__assume_aligned' was not declared in this scope
     __assume_aligned(v, 64);
```

CC --version
`g++ (GCC) 4.8.2 20131016 (Cray Inc.)`

**Comment by bcumming** [comment]
`__assume_aligned` is an intel-only intinsic. I use it and  `__assume(n%16==0)` to ensure vectorization with no clean up before and after the aligned vector loop, which matters for short arrays.

**Comment by jgphpc** [comment]
- https://www.nersc.gov/users/software/compilers/intel-fortran-c-and-c/intel-bug-reports/c-11-header-files-appear-missing-on-edison/

```
module swap PrgEnv-cray PrgEnv-intel
module load gcc
CC -fast -std=c++11 cache.cpp
```
